name: Download and Archive VODs

on:
  workflow_dispatch:

jobs:
  process-vods:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # Fuerza la ejecución secuencial; si prefieres paralelismo, quita esta línea
      matrix:
        # Se definen los chunks de 34 a 1, asegurando que se ejecute primero el 34
        chunk: [34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.13.2'

      - name: Install dependencies and setup work directory
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install internetarchive yt-dlp
          sudo mkdir -p /mnt/workspace/
          sudo chown -R $USER:$USER /mnt/workspace/

      - name: Create/modify ia.ini file
        run: |
          mkdir -p ~/.config/internetarchive
          echo "[s3]" > ~/.config/internetarchive/ia.ini
          echo "access = 7Anjv2BGCRVFCsCS" >> ~/.config/internetarchive/ia.ini
          echo "secret = RxzXP9h0D82Zb2Tl" >> ~/.config/internetarchive/ia.ini
          echo "" >> ~/.config/internetarchive/ia.ini
          echo "[cookies]" >> ~/.config/internetarchive/ia.ini
          echo "logged-in-user = dripzurek%40protonmail.com; expires=Sun, 29-Mar-2026 03:36:56 GMT; Max-Age=31536000; path=/; domain=.archive.org" >> ~/.config/internetarchive/ia.ini
          echo "logged-in-sig = 1774755416%201743219416%20HbSwQJ8wJQoF00FXcsrHfehg6ZwF5GfRiqUnOkkQHdkCf7KjNIFLFmbr1B1sBg1T1Cw1%2FU68gUOFhtDN3gwvN%2Be7sPgkuVoYuJsviUnjPNL2%2BJAoHXAIxIDeTnOoxrKLG1ZTKWitwyUMFF91dBVWOt76LaJ41Q1C95sU%2BKLduWqmQKq4htAtJnvd4kTbQYgGME7ef0e9JTKswYbatrHJtsBbyZMwEEoPhri3zk%2BCCxaG9ff00pDUFeyQ%2FM1jfZsVPE7NgZOzDKKGk%2B%2FIkYFG8CP4dGFtGAJIgpcDitdSGR9fZpFJFW%2B2835099WubrItFPdeJodJk%2BmMf0JaA6EfXg%3D%3D; expires=Sun, 29-Mar-2026 03:36:56 GMT; Max-Age=31536000; path=/; domain=.archive.org; HttpOnly" >> ~/.config/internetarchive/ia.ini
          echo "" >> ~/.config/internetarchive/ia.ini
          echo "[general]" >> ~/.config/internetarchive/ia.ini
          echo "screenname = dripzurek169" >> ~/.config/internetarchive/ia.ini

      - name: Copy repository content to workspace
        run: cp -R $GITHUB_WORKSPACE/* /mnt/workspace/

      - name: Run download and upload for each chunk
        working-directory: /mnt/workspace/
        run: python download_script.py output_vods_chunk_${{ matrix.chunk }}.json
