name: Bedrock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Git LFS
        run: |
          sudo apt update
          sudo apt install git-lfs unzip
          git lfs install

      - name: Replace bedrock_server binary
        run: |
          
          unzip -o bedrock-server-1.21.81.2.zip bedrock_server

      - name: Run Minecraft Server
        run: |
          # Instalar y configurar Playit
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install playit

          wget https://raw.githubusercontent.com/mazurikian/test/ea4a112cfeefe876ee8db55c549e2ae51c8eb74d/playit.toml
          mkdir -p /home/runner/.config/playit_gg/
          mv playit.toml /home/runner/.config/playit_gg/playit.toml

          playit &

          # Ejecutar el servidor
          timeout 350m bash -c 'LD_LIBRARY_PATH=. ./bedrock_server' || true

      - name: Track large files with Git LFS (excluding bedrock_server)
        run: |

          # Buscar archivos mayores a 100 MB (excluyendo bedrock_server)
          find . -type f -size +100M ! -name bedrock_server | while read file; do
            echo "Tracking large file with Git LFS: $file"
            git lfs track "$file"
          done
          git add .gitattributes

      - name: Commit and Push Changes (excluding bedrock_server)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git reset bedrock_server || true  # Asegurarse de no incluirlo

          if ! git diff --cached --quiet; then
            git commit -m "Auto-commit: Minecraft server changes $(date)"
            git push
          else
            echo "No changes to commit"
          fi
