name: Download and Archive VODs

on:
  workflow_dispatch:

jobs:
  process-vods:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # Fuerza la ejecución secuencial; si prefieres paralelismo, quita esta línea
      matrix:
        # Se definen los chunks de 34 a 1, asegurando que se ejecute primero la 34
        chunk: [32]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.13.2'

      - name: Install dependencies and setup work directory
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install internetarchive yt-dlp
          sudo mkdir -p /mnt/worskpace/
          sudo chown -R $USER:$USER /mnt/worskpace/

      - name: Create/modify ia.ini file
        run: |
          mkdir -p ~/.config/internetarchive
          echo "[s3]" > ~/.config/internetarchive/ia.ini
          echo "access = ocGTpZVQQrhQvtXU" >> ~/.config/internetarchive/ia.ini
          echo "secret = jDRRY0sU2lm0gAfl" >> ~/.config/internetarchive/ia.ini
          echo "" >> ~/.config/internetarchive/ia.ini
          echo "[cookies]" >> ~/.config/internetarchive/ia.ini
          echo "logged-in-user = drip.zurek%40protonmail.com; expires=Sun, 29-Mar-2026 17:44:50 GMT; Max-Age=31536000; path=/; domain=.archive.org" >> ~/.config/internetarchive/ia.ini
          echo "logged-in-sig = 1774806290%201743270290%20NqCByg21rnpF%2FyR3n0qzLI4hNspi87TM3TgBYRvn5VUe2VuE8hR%2BlX5Xljl1a1XA%2FCondIFSodG8qTIfbyF25yYu%2FtxXwDC4MIuTCQuSYqmdvj0loB4rEL%2BBLZdy%2BF6EXGV%2B5BQ3QQF%2BUTWDByYzobRDRcC5egzlu7OS%2FbLzlYo5EckzLj7lCvxV1d4BvTPIyrO8g%2FampRi9Id2cbT9FtMIskmVb%2BwZRpMSeCk9hby2zGov8fEU4LWlgKkmm9%2FJOcZ7xKbsEBhT2knqYbCwEOe55KyRcRzVGlJXsvV66fimADzMzf%2FGvbKCJj2ZTXvKv2iu0Kazsxy%2F85hs8gu2dlA%3D%3D; expires=Sun, 29-Mar-2026 17:44:50 GMT; Max-Age=31536000; path=/; domain=.archive.org; HttpOnly" >> ~/.config/internetarchive/ia.ini
          echo "" >> ~/.config/internetarchive/ia.ini
          echo "[general]" >> ~/.config/internetarchive/ia.ini
          echo "screenname = dripzzurek" >> ~/.config/internetarchive/ia.ini

      - name: Copy repository content to workspace
        run: cp -R $GITHUB_WORKSPACE/* /mnt/worskpace/

      - name: Run download and upload for each chunk
        working-directory: /mnt/worskpace/
        run: python download_script.py output_vods_chunk_${{ matrix.chunk }}.json
