name: Internet Archive

on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_URL:
        description: "Download URL"
        default: "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jquery-speedtest/100MB.txt"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install internetarchive
          sudo mkdir -p /mnt/workspace
          sudo chown $USER:$USER /mnt/workspace

      - name: Download file
        working-directory: /mnt/workspace
        run: |
          wget --no-check-certificate --content-disposition "${{ github.event.inputs.DOWNLOAD_URL }}"

      - name: Get file name
        working-directory: /mnt/workspace
        run: |
          FILE_NAME=$(ls)
          echo "FILE_NAME=$FILE_NAME" >> "$GITHUB_ENV"

      - name: Configure Internet Archive
        run: |
          ia configure --username "dripzurek@protonmail.com" --password "@Dripzurek"

      - name: Upload file to Internet Archive
        working-directory: /mnt/workspace
        run: |
          DATE=$(date +"%Y%m%d")
          SAFE_IDENTIFIER=$(echo "$FILE_NAME" | tr "[:upper:]" "[:lower:]" | sed -E "s/[^a-z0-9._-]+/-/g" | sed -E "s/^[._-]+//")
          IDENTIFIER="${SAFE_IDENTIFIER}-${DATE}"
          ia upload "$IDENTIFIER" "$FILE_NAME" --metadata="title:$FILE_NAME" --metadata="mediatype:data" --metadata="collection:opensource_media"
