name: Upload Video to YouTube

on:
  workflow_dispatch:

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Prepare environment
        run: |
          sudo mkdir -p /mnt/workspace
          sudo chown $USER:$USER /mnt/workspace

      - name: Install dependencies
        run: pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests oauth2client tqdm && sudo apt update && sudo apt install ffmpeg

      - name: Download first half of video
        working-directory: /mnt/workspace
        run: |
          DURATION=$(ffmpeg -i "'https://stream.kick.com/ivs/v1/196233775518/V3f9DWwe2lks/2025/4/1/16/15/JwdvOAppHrfG/media/hls/1080p60/playlist.m3u8" 2>&1 | grep "Duration" | cut -d ' ' -f 4 | sed s/,//)
          MIDPOINT=$(ffmpeg -i "'https://stream.kick.com/ivs/v1/196233775518/V3f9DWwe2lks/2025/4/1/16/15/JwdvOAppHrfG/media/hls/1080p60/playlist.m3u8" 2>&1 | grep "Duration" | awk -F: '{print ($2*60) + $3/2}')
          
          ffmpeg -i "'https://stream.kick.com/ivs/v1/196233775518/V3f9DWwe2lks/2025/4/1/16/15/JwdvOAppHrfG/media/hls/1080p60/playlist.m3u8" -c copy -t ${MIDPOINT} part1.ts
          wget https://github.com/mazurikian/test/raw/refs/heads/main/oauth2.json
          wget https://github.com/mazurikian/test/raw/refs/heads/main/script.py

      - name: Upload part 1
        working-directory: /mnt/workspace
        run: |
          python script.py part1.ts "Video Parte 1"
          rm part1.ts

      - name: Download second half of video
        working-directory: /mnt/workspace
        run: |
          ffmpeg -i "'https://stream.kick.com/ivs/v1/196233775518/V3f9DWwe2lks/2025/4/1/16/15/JwdvOAppHrfG/media/hls/1080p60/playlist.m3u8" -c copy -ss ${MIDPOINT} part2.ts

      - name: Upload part 2
        working-directory: /mnt/workspace
        run: |
          python script.py part2.ts "Video Parte 2"
          rm part2.ts
